deployment:
  image:
    repository: 381492074864.dkr.ecr.ap-northeast-2.amazonaws.com/dolphindance-api
    tag: "4c988c"
  imagePullSecrets:
  - name: aws-credentials

  secretEnv:
    enable: true
    names: 
      - aws-credentials

service:
  type: ClusterIP
  
  # port setting
  port: 3000
  targetPort: 3000
  protocol: TCP
  name: dolphindance-dev
